src/rm.js

Fix issue #49: Retry rmdirSync on Windows for up to 1 second if files still exist.

---

bin/shjs

I just encountered an issue when executing my script placed in a directory with spaces in the name. Please take a fix!

Wrap script name in double quotes

---

src/which.js

Was viewing the source and noticed this random doodle-:bug:

remove empty for loop and leaked i var

---

bin/shjs

This is similar to #168, but with more targeted changes.

Support exit code in shjs.

---

.gitignore
README.md
shell.js
src/touch.js
test/touch.js

Add the `touch` command based on the [manpage](http://linux.die.net/man/1/touch)

add touch(1)

---

src/common.js
src/echo.js

Don't do `console.log.apply(this, ...)`.

---

.travis.yml

Just adding OS X to the CI, since this should be supported (and it was very easy to add). If this PR fails, then it'll point out some bugs that we have to track down.

chore(travis): add OS X to Travis CI

---

README.md
src/ln.js
src/mkdir.js
src/mv.js
src/touch.js

I also fixed a URL in the top section of the README.

style: make docs more consistent

---

package.json
test/resources/shjs/a-file.js
test/resources/shjs/coffeescript.coffee
test/resources/shjs/exit-0.js
test/resources/shjs/exit-codes.js
test/resources/shjs/stdout-stderr.js
test/shjs.js

test(shjs): add tests for shjs

---

src/ln.js
test/ln.js

Fix relative symlinks

---

.lgtm
MAINTAINERS

chore(LGTM): add LGTM config files

---

appveyor.yml

Add appveyor.yml config file

---

src/ln.js
test/chmod.js
test/cp.js
test/ln.js
test/pushd.js
test/test.js

Fixes #294 partially and #296.

Fix tests on Windows

---

README.md
src/sed.js
test/sed.js

fixes #231. Semantics are like unix sed.
Also, if we merge this, it makes the PR to add support for pipes slightly nicer.

feat(sed): support multiple file names

---

test/which.js

This is an example PR for how to make PRs against #317.
Current Lint Problem Count for this branch: 1516 (Three less than #317!)

style(test/which): make test/which.js conform to the style guidelines

---

src/ln.js
test/ln.js

Fixes symlink creation on Windows systems and adds a test
for symlinking directories since it needs special treatment
on Windows.
Fixes #301.

Fix symlinking on Windows

---

README.md
src/which.js
test/which.js

Redo of #134.
Since it was only a few lines, it was easy to rewrite against master.

Search PATHEXT instead of 3 hardcoded values

---

.gitignore

Ignores more Node/NPM files and adds ignore rules for the following:
- Linux
- OS X
- Vim
- JetBrains IDEs

Rewrite .gitignore to be more comprehensive

---

.travis.yml
README.md
package.json

Drop Node `v0.10` support and document.

chore: drop node v0.10 support

---

README.md

As per:
https://github.com/dthree/cash/pull/24#
:)

Add Cash cross-reference

---

bin/shjs
package.json
scripts/run-tests.js
src/exec.js
test/config.js
test/echo.js
test/exec.js
test/make.js
test/set.js
test/shjs.js
test/touch.js

This is a redo of #258, since it looks like it may have been abandoned.

feature: use rechoir

---

package.json

Since we're actually not the first result when you search on npm for "shelljs", and we probably should be...
Let me know if there are any other keywords we should change.

Add shelljs as a keyword in package.json

---

README.md
shell.js

Pretty trivial change, just wanted to see what @ariporad thinks of it. It gives a shoutout to the two most popular projects in the wiki.

docs: add link to wiki page

---

src/common.js
test/common.js

Fixes #372 and adds a test to check for this.

fix: error message now printed for fatal failures

---

scripts/generate-docs.js
scripts/run-tests.js
shell.js
src/common.js

I realized that our code base can be somewhat confusing in key areas. This should help clarify some of the more confusing parts for other contributors.

docs: comment code better to help contributors

---

src/cp.js
test/cp.js

fix(cp): -n option no longer raises error

---

README.md

Similar to shelljs/shx#70, but also keeps badges consistent with shx

chore: switch to shields.io, and add npm badge

---

src/mkdir.js

closes #468 
This is the same PR, but with style fixes.

Fix mkdir malformed path

---

src/mkdir.js
test/mkdir.js

Fixes #473 
@ariporad, ready for review

fix: mkdir for invalid perms does not kill process

---

README.md
src/head.js
src/tail.js

fixed head/tail readme

---

README.md

This shows # of downloads per month, which I think is a useful stat to display on our README.

chore: add downloads per month on README

---

src/common.js
src/cp.js
src/exec.js
src/grep.js
src/head.js
src/ln.js
src/ls.js
src/mkdir.js
src/mv.js
src/rm.js
src/sed.js
src/tail.js
src/to.js
src/toEnd.js
test/plugin.js

This implements the following options: `continue`, `code`, `prefix`, & `silent`.
Fixes #522, #523

feat: plugin.error() takes an options parameter

---

.travis.yml
README.md
appveyor.yml

chore: add Node v7 for CI

---

src/rm.js

Fix lint warning

---

MAINTAINERS
package.json

Add Brandon Freitag to maintainers/contributors

---

README.md
src/sed.js

Update sed documentation regarding capture groups

---

ava-test/echo.js
src/echo.js

Add newline to output of echo

---

src/common.js

Add ability to configure error from parseOptions

---

src/common.js

Use Object.assign if possible

---

.lgtm
MAINTAINERS

Remove files related to lgtm.co

---

ava-test/rm.js
src/rm.js

Fix: rm behavior regarding symlinks

---

ava-test/common.js
src/common.js

Throw an error if the options string does not start with '-'

---

.eslintignore

Ignore test temp directories during linting

---

README.md
ava-test/echo.js
src/echo.js

Add "-n" option to echo

---

RELEASE.md

docs(release): use bulleted list

---

src/common.js

Safely exit by throwing an error

---

.travis.yml
README.md
package.json
src/common.js
src/exec.js
src/tempdir.js
test/exec.js

Chore drop 0.12

---

src/rm.js
test/rm.js
test/utils/utils.js

Adds support for removing fifos.
Fixes #617

Add support for removing fifos

---

README.md
shell.js

Hi, just though this might be useful for someone. I had to run a test manually to see if custom exec commands also show up as verbose.

Small clarification of verbose flag

---

src/common.js
src/cp.js
src/find.js
src/ln.js
src/which.js
test/cp.js
test/test.js

Refactor: Use process.platform across codebase

---

src/common.js
src/cp.js
src/head.js
test/common.js

Add common.buffer

---

.travis.yml
appveyor.yml

Add node 8 to CI

---

README.md

Remove PDF.js mention from README.md

---

.github/ISSUE_TEMPLATE.md

Fixes #787 
Adds a note to the issue template that links to the FAQ.

Add note to issue template about FAQ

---

.travis.yml
appveyor.yml

chore: update CI to Node v9

---

README.md

docs: announce plugin API

---

appveyor.yml

This changes appveyor to run the entire test matrix, even if a failure
occurs early on. This is helpful for debugging.

chore(appveyor): run entire test matrix

---

.travis.yml

This removes gitter integration with the project. I don't monitor gitter
right now, and I've never noticed the integration to be particularly
useful otherwise.
Test: N/A

chore: remove gitter integration

---

README.md
src/exec.js

This is a follow-up to #950, to emphasize the message.

docs(exec): minor wording changes on security doc

---

README.md
src/ls.js

Adding an example of using ls with globs. Will generate the README soon.

Update ls with glob example.

---

src/mkdir.js

fix(mkdir): mitigate directory creation race condition

---

README.md
src/test.js

`test('-f', path)` : true if path is a regular file
`!test('-f', path)`: true if path is not a regular file

Fix test command example

---

.github/SECURITY.md

No change to code. This adds a security policy.
Issue #1058

chore: add SECURITY.md

---

src/sed.js
test/sed.js

Fixes [issue #159](https://github.com/shelljs/shx/issues/159) with shx

sed with -i option now runs silently

---

README.md
shell.js
src/errorCode.js
test/grep.js
test/ls.js

This PR is for part of [#1013](https://github.com/shelljs/shelljs/issues/1013), and aims to implement ```shell.errorCode()```, similar to ```shell.error()```.  Please let me know if you'd like me to change something, and thank you for the chance to work on a new ShellJS feature!

Feature: Expose Error Code

---

src/tail.js
test/tail.js

Hello, I wanted to contribute by trying to fix issues #984 and consequently #983. I hope my solution behaves as expected, I performed several tests and I think I got the point, otherwise please let me know and I'll find a remedy. Thank you!

Added support for -n +NUM in tail.js (with sign)

---

test/cp.js

This fixes several issues with the cp -Ru test cases:
* Originally, I noticed the touch syntax looked wrong
* After fixing that, I was trying to figure out how the test case was
even passing before. I realized one of the assertions was wrong (it
was asserting sourceFile contents, but should have asserted destFile
contents)
* I realized the test should have created a nested destination
directory; without proper nesting, the sourceFile never actually
collided with destFile during the copy
* Lastly, I swapped touch() usage to use hardcoded timestamps for test
consistency

test(cp): fix cp -Ru test cases

---

.github/workflows/main.yml

This is supposed to fix codecov.
Fixes #1124

chore: add codecov token

---

.github/workflows/main.yml

This PR bumps two GitHub workflow actions to their latest versions.

Bump GitHub workflow actions to latest versions

---

README.md
plugin.js
src/dirs.js
src/sed.js
test/cp.js
test/rm.js

This PR fixes a few typos that I spotted in the project. I will sign my commit soon.

Fixing typos

---

test/config.js

No change to logic. This adds tests for more `config.globOptions` values. This aims to cover the options which appear to be supported by both node-glob and fast-glob, however the options have different names in each module. This is a followup to PR #1163.
See https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#compatible-with-node-glob
Issue #828

test: add more coverage for globOptions

---

README.md

Update list of project maintainers.

chore: update maintainers list

---

.npmrc
package-lock.json

No change to logic. This commits the package-lock.json file because we've since dropped support for old Node versions.

chore: commit package-lock.json

---

README.md
RELEASE.md

No change to logic. This updates the main branch name.

chore: rename master -> main
