shelljs/shelljs

- package.json
- src/exec.js
So as to keep CPUs happy.
[relevant XKCD on why this may be a bad idea](https://xkcd.com/1172/)
> Use new child_process.execSync instead of busywaiting

- make.js
This implements a change that allows `--` to indicate arguments to be passed to `make` targets. Basically, you can do this:
```js
target.foo = function(args) {
};
```
And `args` will be everything after the `--` on the command line, so for example:
```
$ node Makefile.js foo -- bar baz
```
`args` in the previous code will be `['bar', 'baz']`.
I noticed there's a `force` argument for targets, but I couldn't find anywhere it's documented or used. So, I moved it to be the second argument as it seems mostly unused at the moment.
Other caveats:
1. It appears there aren't any tests for `make.js`, so I didn't know if it's okay to just make changes. I did test it locally with an example file and it worked
1. `npm test` fails for me (I'm on Windows using Git Bash) and I couldn't figure out how to …
> Breaking: Allow -- as args separators (fixes #188)

- src/exec.js
fixes #206 
Was unable to write a reliable test but the following failed about half time without the change and did not fail with the change
```coffee
shell.exec('git checkout -')
```
I'm convinced this is the appropriate fix based on the [documentation](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) as we are piping two readable streams to a writeable stream and if one ends and the other writes later we get a "write after end". The ends of the std streams does not appear to be consistent.
> prevent internal error: write after end

- src/exec.js
Solves the stream closing issue introduced by pull [#214](https://github.com/arturadib/shelljs/pull/214).
According to the [Node Docs](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options), `process.stderr` and `process.stdout` are closed when the process exits - we can listen to this and close the `stdoutStream` accordingly
> Manually closing streams

- make.js
For a current make script I was unable to use promises as the task had previously ran.
This commit it makes it so the targets still return a result even if they have been ran. This makes it so that the promises can still be used.
> Memoized the result of target invocation

- README.md
The `cat 'macro.js'` needs parentesis to not include `file`. The current coffeescript compiles to the following:
```javascript
sed('-i', /.*REPLACE_LINE_WITH_MACRO.*\n/, cat('macro.js', file));
```
> Fixed coffeescript syntax in top example

- src/chmod.js
- test/chmod.js
If you call:
shelljs.chmod('a-rwx,u+rw', 'file');
shelljs.chmod('a-rwx,u+rw', 'file');
Then the file will have no permissions (mode 000). This is because the permissions at the beginning of the second call are 600, and when the 'u+rw' is processed, it compares the final mode (600) with the original mode (now outdated due to 'a-rwx', but 600) and does not run the operation if they are the same.
This PR adds a few more multi-symbolic tests, and resets 'perms' to 'newPerms' after running fs.chmodSync() to allow examples like 'a-rwx,u+rw' to work correctly even if the original file permission was already set as desired.
> Fixes an issue with multi-symbolic mode specification (ie a-rwx,u+rw)

- src/test.js
"symbolic" was misspelled. This wasn't properly fixed in #221 (generating docs used to revert the fix).
> docs(spelling): fix typo in source comment

- src/tempdir.js
The checked method on `os` module was `tempDir` which was not existing on any version of Node (should have been `tmpDir`). With Node 0.10, the name became `tmpdir`.
> Fix `os.tmpdir` bug

- README.md
- src/common.js
- src/exec.js
- test/cp.js
- test/exec.js
- test/mkdir.js
- test/mv.js
- test/pushd.js
- test/utils/utils.js
This is a fix for #267. The new behavior can be seen to be as such:
```
$ # assume that fake1, fake2, and fake3 do not exist
$ cat test.js
require('shelljs/global');
ls('fake1', 'fake2', 'fake3');
$ shjs test.js
ls: no such file or directory: fake1
ls: no such file or directory: fake2
ls: no such file or directory: fake3
```
This is comparable to the Bash behavior:
```
$ ls fake1 fake2 fake3
ls: cannot access fake1: No such file or directory
ls: cannot access fake2: No such file or directory
ls: cannot access fake3: No such file or directory
```
Fixes #267, #209.
> Commands that have multiple errors now produce cleaner log output

- package.json
The package.json still used the old `arturadib` github URL. This is now updated for the new `shelljs` URL. This will save someone an HTTP redirect.
> chore: update github URL in package.json

- README.md
- src/exec.js
Re-implementation of #185 (I didn't have the old fork anymore)
The [exec docs](http://documentup.com/arturadib/shelljs#command-reference/exec-command-options-callback) specify:
> **exec(command [, options] [, callback])**
> Available options (all false by default):
> `async`: Asynchronous execution. Defaults to true if a callback is provided.
> `silent`: Do not echo program output to console.
That seems to imply to me that the following code can be written:
```javascript
exec("sleep 0.5", {async: false}, function() {
echo("print first");
});
echo("print last");
```
which prints:
```
print last
print first
```
After looking at the code, however, it is clear that `options.async` is overridden to `true` if a callback is provided. This PR updates the README to be more in line with the code. …
> update `exec` docs to match implemented behaviour

- src/cp.js
- test/cp.js
- test/rm.js
> Fix cp to match unix behavior

- scripts/generate-docs.js
- scripts/run-tests.js
- src/chmod.js
- src/error.js
- src/exec.js
- src/pwd.js
- src/rm.js
- src/which.js
`run-tests.js` previously relied on shell wildcard expansion, and did not specify
full paths. This uses common.expand to handle globbing internally, and specifies
the full path, so jshint can find all the files.
This **does not** entirely fix `run-tests`, but this does fix the jshint portion, so we'll at least get it to process javascript files. A full fix would be much more intensive, since `exec()` can't start from the current working directory. So this is only a partial fix for #294.
Also, this adds in lint-checking the `scripts/` folder (and fixes the lint errors I found!). Now the only significant folder this skips is the `src/` folder (which I'm working on providing support for).
> fix: jshint works on Windows

- src/cd.js
- src/common.js
- test/cd.js
I added a `previousDir` field to `common.state` to allow the `cd()` function to have this option. I also added unit tests for this behavior.
Usage is as follows:
```Javascript
// Setup
mkdir('foo');
mkdir('bar');
cd('foo');
cd('../bar');
echo(pwd()); // outputs "/path/to/bar"
cd('-'); // jump back
echo(pwd()); // outputs "/path/to/foo"
cd('-'); // jump back again
echo(pwd()); // outputs "/path/to/bar"
```
> Implementing cd('-') to behave like Bash's "cd -"

- src/common.js
- test/cd.js
This adds tilde expansion to the expand() function. Arguments starting with '~/'
will have the tilde expanded to the user's home directory, as with Bash.
Also, if an argument is simply `~`, then it will expand to the home directory as well.
```Javascript
> cd('~'); // Go to home directory
> ls('~/*.js'); // Look for all .js files
> cd('~/..'); // Go to /home, /Users, or C:\Users
```
This does not support all of Bash's tilde expansion (not sure if this would be difficult). For example:
```Bash
$ ls ~otheruser # look into otheruser's home folder
$ # Nothing like this is supported in ShellJS
```
> feat: add tilde expansion to expand()

- README.md
- src/cd.js
- test/cd.js
`cd()` used to be a error. Now it changes to the home directory instead. This is to match unix behavior:
```Bash
$ pwd # prints whatever the cwd is
$ cd
$ pwd # prints the home directory path
```
> feat(cd): cd() (no args) changes to home directory

- src/sed.js
- test/grep.js
- test/resources/grep/file
- test/sed.js
`sed()` will now convert search strings to regex form, so `'a*'` will now work like `/a*/`. Also, new tests for grep and sed ensure that `*` is not expanded for filename globbing.
While the filename globbing isn't currently an issue, I anticipate that it could be a problem if we don't handle `sed()` and `grep()` carefully when doing filename globbing as part of the `wrap()` function (which I think is the way this project should go). These tests are an extra guard to make sure we don't make any mistakes.
So this should probably be merged before #275 to be safe.
> fix: regexes are more consistent with sed and grep

- package.json
We don't really guarantee our stuff works on v0.8, since travis doesn't run on that version (this is because jshint requires v0.10+). So this just removes it from package.json. This doesn't prevent v0.8 users from using shelljs, just removes the promise of support.
See #307 for a discussion about this.
> chore(package): remove v0.8 from engines list

- .travis.yml
- scripts/generate-docs.js
This fixes an issue (#309) where the gen-docs script's sed() command would improperly
update the docs.
As a bonus, Travis now checks that docs are generated properly (or, more specifically, that no files have been changed by running the tests and re-generating docs, which is exactly what we want). This prevents breaking changes in `sed()` from going unnoticed. This will also prevent people from modifying doc-comments in the source files without generating docs, or by modifying the README manually without changing comments.
> fix(gen-docs): fix issue where docs are generated wrong

- test/shjs.js
Prefix `shjs` commands with`node ` for Windows, since Windows doesn't use shebangs.
Blocks #297
> fix(windows): fix shjs commands for windows

- README.md
- src/ls.js
- test/ls.js
The `-l` option will now cause `ls()` to return an object containing file stats.
These objects will also have a toString() method that formats it into something
analogous to `ls -l`'s output format.
This is useful in the case of `ls('-l', 'dir/').join('\n')`, which will now have formatting similar to unix's `ls -l`.
The mechanics for `-l` are based off #137. This resolves feature request #323.
> feat(ls): add -l  option

- README.md
- src/common.js
- src/mv.js
- test/common.js
- test/mv.js
This lets `mv()` have `-f` as the default behavior (the flag exists for legacy reasons). I introduce the `-n` flag, which will allow the opposite behavior. This is the default behavior on Bash.
This also introduces a modification to `parseOptions()`, allowing dictionaries to be specified of the following form:
```Javascript
options = common.parseOptions(options, {
'f': '!no_force', // the boolean opposite of "no_force"
'n': 'no_force'
});
```
The empty string will still cause `no_force` to default to false, as it normally would. Options prefixed with `!` have the special meaning that the appearance of that commandline flag sets the option to `false` instead of `true`. So passing the `-f` flag will cause `options.no_force` to be `false`.
If someone passes in a flag like `-fn`, this will …
> fix(mv): add -n option, make -f default behavior

- README.md
- shell.js
- src/common.js
- src/set.js
- src/touch.js
- test/set.js
Add new set() command as a wrapper for `config` variables. This takes the `-e`, `-v`, `+e`, and `+v` flags.
This is based off (and replaces) #149, which introduced the `logCmd` option. This also adds `set()` as a nice wrapper for interfacing with the variables.
`config.verbose` will log each command in a unix-y kind of format. For example, `ls('dir/')` logs as `ls dir/` (strips parens, strips surrounding quotes). This is mostly just because it was easier to implement this way.
I left the docs for `config.fatal` (and added docs for `config.verbose`), although we might also consider deprecating those and encouraging the use of the equivalent `set()` commands instead (to trim down on documentation). One issue is that `config.silent` does not have an analogous [`set` …
> feat(set): add new set() command

- README.md
- src/cp.js
- test/cp.js
Fix default behavior for `cp()` for bash compatibility. This replaces #325, and is done in a similar style to #328
> fix(cp): add -n option, make -f default behavior

- README.md
- src/exec.js
- test/exec.js
- test/resources/exec/slow.js
This allows any option from https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback to be passed through our `shell.exec()` function to the native `exec()`/`execSync()`.
This fixes #250, #132 and replaces #270 #284 #333 #163 
This specifically tests the `cwd`, `maxBuffer`, and `timeout` options, since those were requested.
> feat(exec): allow all exec options to pass through

- README.md
Other than the CoffeeScript section
@nfischer: Ready for review
> docs(README): remove coffeescript from README

- src/common.js
- src/touch.js
- test/common.js
- test/exec.js
- test/resources/exec/slow.js
- test/touch.js
This improves `parseOptions` to allow options of the form:
```
touch({'-r', 'path/to/file'}, 'other-file.txt');
```
to supply a value to an option. In this example, `-r` has the string value `'path/to/file'`.
> fix(touch): enhance parseOptions and fix touch's -r flag

- README.md
- src/grep.js
- test/grep.js
`grep -l` will only print filenames of matching files.
Sort-of replaces #116. I can add `-s` support if we want to completely close that PR.
> feat(grep): add -l option

- src/exec.js
- test/exec.js
Looks like #335 doesn't work perfectly with all options. This is because `execSync` does 2 calls to `exec()`, and some options need to be passed to both calls.
This should clean things up a bit, and fix the issue for the `shell` option, which would actually fix #138 and #208.
> fix(exec): now actually supports shell option

- src/exec.js
- test/exec.js
Fixes #353 
The issue had to do with an exception being thrown, causing `execSync()` to skip the cleanup. This seems to fix the issue for each version of node we support
> fix(exec): temp files are now cleaned up

- shell.js
- src/cat.js
- src/chmod.js
- src/common.js
- src/mv.js
- src/rm.js
- src/sed.js
- test/ln.js
- test/ls.js
- test/mkdir.js
- test/sed.js
- test/test.js
- test/to.js
- test/toEnd.js
- test/touch.js
Fixes #343. This performs glob expansion on commands, where it makes sense. This doesn't glob for:
- `pwd()` (it doesn't take any arguments)
- `test()` (globbing here is very unreliable in bash)
- `exec()` (this actually **does** glob-expand, but that's done in the shell itself (`/bin/sh`), not by this function
- `set()` (globbing doesn't make sense)
- `tempdir()` (it doesn't take any arguments)
Some other commands we might want to not permit to glob (because it isn't useful, and I suspect globbing slightly hampers performance) would be:
- `which()`
- `mkdir()`
I had to modify some test cases that didn't actually have correct behavior (the `ls('path/*')` cases were often wrong). I also added a lot of new test cases for globs on commands that didn't previously have them.
I think this …
> feat(glob): glob support for (almost) all commands

- .gitattributes
Fixes cat, ls, and sed tests on Windows when Git line ending configuration is set to auto.
> Consistently use LF line endings

- .npmignore
This ignores the `.gitattributes` file
> Ignore gitattributes from npm package

- README.md
- src/common.js
- src/set.js
- test/set.js
See the docs for `set('-f')`. This is analogous to Bash's functionality.
It's a nice option to have safer code for the bulk of the utilities (this doesn't affect `exec()` *yet* but this will disable globbing for that too once that's an option)
Fixes #344
> feat(set): add -f option to disable globbing

- package.json
- src/common.js
- src/cp.js
- src/grep.js
- test/cp.js
Switch to the glob module to do shell globbing. Fixes a bug in `cp()` where
hidden files were not copied recursively.
Replaces #275, fixes #225. This is a less-aggressive version of #275 (doesn't modify `ls()` nearly as much). We should probably add some more glob-related tests though, like `file?.txt` and things of that sort.
I wrote this up because this will fix one of the bugs I found when writing the `ShellString` refactor for free.
For what it's worth, this does hurt performance slightly (it takes 16 seconds on average to run `npm test` instead of 15 seconds), but not by very much. We might be able to get that performance back some other way.
Closes #275, #225.
> feat(glob): use glob module for globbing

- README.md
- src/touch.js
- test/touch.js
Does what it says. From the (updated) docs:
> touch([options,] file [, file ...])
> touch([options,] file_array)
This is consistent with the API for `ls()`, `cp()`, `mv()`, `rm()`, etc.
> feat(touch): supports multiple files

- README.md
- shell.js
- src/common.js
- test/exec.js
- test/set.js
Hi everyone!
This PR adds a 'config.throw' option to throw errors from shell commands. Config.fatal is useful, but it doesn't log stack traces, which makes deep errors hard to find. This 'throw' option is useful in synchronous scripts where you have try / catch handling, or you want the default behavior of printing a full stack trace and exiting.
Thanks!!
> config.fatal now throws an exception

- shell.js
- src/common.js
- src/echo.js
- test/set.js
This fixes a couple issues with `config.verbose` logging, and some related things.
- `set('-v')` previously didn't log `echo()` commands because those weren't `common.wrap`'ed
- `echo()` is now wrapped, but is designed to still allow echoing strings that start with "-" (ex. "-1*3+5") (see issue #20)
- `echo()` still does not glob. This is because 1. globbing isn't that useful for `echo()` in my opinion, and 2. echo is frequently used enough that it should have good performance by default
- internal errors are now outputted to stderr instead of stdout
- `set('-v')`-style logging goes to stderr, not stdout. This resembles Bash's behavior with `set -v`
The way this is implemented, `echo()` still doesn't support any options, but we may want to consider allowing for that in the future (`-n` …
> fix(verbose): verbose-style logging is consistent

- test/ln.js
Add tests for symlinking to `./` (this closes #363 if the behavior here is correct). If this behavior is not posix behavior, we should fix this instead.
> test(ln): add tests for linking to cwd

- src/exec.js
This fixes #17. This is based off #263, but it also escapes quotes in the path.
The issue comes from the fact that `exec()` executes a script created in the temporary directory. On unix systems, this is usually `/tmp/`, which has no unusual characters in the name. Windows users usually have a temporary directory that is a subdirectory of their home folder (which has their username as part of the path). Therefore, Windows users with usernames containing either a space or a `"` couldn't use `exec()` properly.
This now properly surrounds the strings with quotes, and escapes any quote characters inside for security, preventing scenarios, such as creating a directory named `/tmp"; echo hijacked; echo "` (perhaps `$TMP` is modified to point there, and this is chosen as the temporary directory). …
> fix(exec): properly handles paths with spaces and quotes

- README.md
- scripts/generate-docs.js
- shell.js
- src/cat.js
- src/common.js
- src/echo.js
- src/exec.js
- src/grep.js
- src/ls.js
- src/pwd.js
- src/sed.js
- src/to.js
- src/toEnd.js
- src/which.js
- test/cd.js
- test/common.js
- test/config.js
- test/cp.js
- test/echo.js
- test/exec.js
- test/grep.js
- test/ls.js
- test/make.js
- test/rm.js
- test/sed.js
- test/to.js
- test/toEnd.js
- test/which.js
This is a PR to refactor commands to return `ShellString` objects instead of regular strings. This still has some broken tests, so it's far from ready, but I think in principle this approach will work.
Feel free to fix any tests and/or post the diffs.
Fixes #356, #154.
> Refactor shellstring

- README.md
- shell.js
- src/cat.js
- src/common.js
- src/exec.js
- src/grep.js
- src/ls.js
- src/sed.js
- test/pipe.js
Fixes #148
Commands can now be piped, of the form:
```javascript
grep('foo', 'file1.txt', 'file2.txt').sed(/o/g, 'a').to('output.txt');
echo('files with o\'s in the name:\n' + ls().grep('o'));
cat('test.js').exec('node'); // pipe to exec() call
```
Commands can send their output to another command in a pipe-like fashion. `sed`, `grep`, `cat`, `exec`, `to`, and `toEnd` can appear on the right-hand side of a pipe. Pipes can be chained. You can even pipe into async `exec()`.
This also improves performance slightly. I got rid of the slow, home-grown `escape()` function inside of `src/exec.js` and replaced it with `JSON.stringify()`, which I measured to be slightly faster, and much more reliable (it properly escapes newlines, tabs, etc. as well).
I couldn't think of any tests to add for piping …
> feat(pipe): add support for pipes between commands

- test/cp.js
This doesn't change anything, it just adds tests. Looks like this was a bug in `v0.6`, but has been since fixed. I'll update this if I don't get feedback from #376 about this.
> Add unit tests to prevent regression (see #376)

- src/cd.js
This increases performance somewhat
> perf(cd): only run `stat` once

- appveyor.yml
This just adds node 4 into the mix for appveyor unit testing (based off the config from [cash](https://github.com/dthree/cash/blob/master/appveyor.yml))
> chore(appveyor): add in node 4 for appveyor

- src/cd.js
- src/common.js
This should be a simple refactor. This uses `process.env.OLDPWD` to store the previous directory (used by `cd -`), instead of a separate variable as we had it. It's a little closer to bash's semantics if we use `process.env`, since now people can run `echo(env.OLDPWD)` and see a useful result.
> refactor(cd): use process.env.OLDPWD to store previous dir

- shell.js
- src/find.js
- src/ls.js
- test/ls.js
This greatly simplifies the implementation of `ls`, and probably makes it a good deal more performant.
> refactor(ls): greatly simplify ls implimentation

- src/cp.js
- test/cp.js
- test/set.js
Fixes issue in #376. Simplifies the code, and slight perf win.
This fixes the semantics of `cp()`, which had deviated from unix `cp` a bit. If anyone is available to review, that would be good.
Goals of this PR:
- improve performance
- improve correctness
> refactor(cp): clean up code and fix #376

- README.md
- global.js
- src/to.js
- src/toEnd.js
- test/global.js
`require('shelljs/global')` extends String.prototype to have the `.to()` and `.toEnd()` methods again. This also adds tests for the global require.
This is along the lines of the discussion in #398. The advantage of this is that ShellJS is still backwards compatible for `require('shelljs/global')`, but we still have an option to avoid extending the String prototype (just use `require('shelljs')` instead). This would make things more convenient (and `global` is a convenience script primarily), and would ease the transition to ShellJS v0.7.
> refactor(string): modify string protoype, but only for shelljs/global

- README.md
- shell.js
- src/cat.js
- src/cp.js
- src/grep.js
- src/mv.js
- src/rm.js
Related to #398 
All commands support wildcards now, so this documents that. It points to the glob module as a reference on globbing (so people know which glob characters are supported).
I also did some other docs cleanups.
Feel free to rebase this off master if you do other merges first.
> docs: wildcards for all commands, other docs cleanups

- test/rm.js
Fixes #332 
This is pretty straightforward. The issue existed on v0.6, but not on master. This just adds the tests to make sure we don't run into this issue again.
In case you're wondering, the "**only -f**" case is indeed bash-compatible. `rm -f real_dir/` is an error, `rm -f fake_dir/` is not (assuming that `fake_dir/` does not exist, of course).
Feel free to adjust the tests as necessary. I checked them against bash on Linux, and this is compatible with that.
> test(rm): add tests to prevent a future regression

- README.md
- shell.js
- src/common.js
- test/config.js
Allow users to customize the settings of `glob.sync()` (if they so-desire). This doesn't change the default behavior.
I imagine this is a feature a few users may want (users wanted something similar for `exec()` options in #163, #284, #132 ).
> feat(glob): expose config.globOptions.

- README.md
- src/cp.js
- test/cp.js
Fix for #407 , includes test case for basic cp -L commands and additional cp -RL test case
> issue-407: Add regular files unit tests and fix symlink copy behavior

- src/rm.js
This just deletes a dangling branch. The `else if` and `else` branches were identical and could be merged.
This was discovered by @j-em [while working on cash](https://gitter.im/dthree/cash)
> refactor(rm): Remove duplicate code

- README.md
- src/exec.js
Also, this links to the breaking changes page of the wiki.
> docs(exec): fix docs about exec return type

- README.md
- src/error.js
This is the PR I proposed in #397. This deprecates relying on `shell.error()` to return an error string. This will give us the freedom to either keep it the same, or change it in the future, but this keeps the actual implementation the same currently.
> docs(error): deprecate relying on string value

- README.md
- scripts/generate-docs.js
This adds a section to the bottom of the README that looks like:
> ## Team
>
> | [![Nate Fischer](https://avatars.githubusercontent.com/u/5801521?s=130)](https://github.com/nfischer) | [![Ari Porad](https://avatars1.githubusercontent.com/u/1817508?v=3&s=130)](http://github.com/ariporad) |
> |:---:|:---:|
> | [Nate Fischer](https://github.com/nfischer) | [Ari Porad](http://github.com/ariporad) |
This also modifies the `generate-docs` script so that it doesn't override this section of the README.
Inspired by @dthree's [cash](https://github.com/dthree/cash) README.
> chore: add "Team" section to README

- src/common.js
- test/ls.js
`ls('empty')` used to have a `.stdout` property of `"\n"`, which is wrong. This fixes that. Trailing newlines are only appended for arrays that have length \> 0.
Once this gets fixed, almost all newline output will be consistent for the various shelljs commands. This is a partial fix for #420 (`pwd()`, `echo()`, and `which()` still need to be fixed).
> fix(ls): no trailing newline for empty directories

- src/common.js
- test/echo.js
This is an issue in the case of `echo(which('fakecmd'))`. This used to succeed
in v0.6 but was broken during the ShellString refactor on the master branch.
> fix: null is no longer confused for an object

- README.md
Might be a good idea, in light of #405 and #406
> docs: warn that README contains newest features

- .travis.yml
- README.md
- test/pwd.js
Looks like node v6 just got released. Just tried this out via nvm and saw that one of our tests broke for node v6, so I fixed that test.
Not sure if appveyor can test against node v6 yet, but I added it to the mix anyway.
> chore: test against node v6

- appveyor.yml
Looks like appveyor now has node 6
> chore(CI): update appveyor

- .editorconfig
- CHANGELOG.md
- RELEASE.md
- package.json
- scripts/changelog.sh
This PR adds the same changelog flow added to `shx`.  Also generates the first changelog.
> chore: setup changelog

- test/ls.js
In response to [this comment](https://github.com/shelljs/shelljs/issues/446#issuecomment-222088271). It appears this behavior doesn't work correctly on OS X 15.5 (but works on ubuntu and windows).
> test(ls): add case for trailing slash on dir name

- README.md
- src/exec.js
Since we had a couple issues about this option.
If you can think of a way to phrase this more clearly and concisely, please go ahead and do so.
> docs(exec): explicitly mention the `shell` option

- package.json
Now you can generate documentation by running `npm run gendocs`. Once this is merged, we can add this as a step to the contributing guidelines along the lines of:
> ### Before committing:
>
>  - Run `npm test` to make sure tests & linting pass
>  - Run `npm run gendocs` to make sure docs are up to date
>
> Is travis-only failing? Make sure you run `npm run gendocs` before committing!
> chore(gendocs): add `npm run gendocs` command

- .jshintignore
- .jshintrc
- .npmignore
- package.json
- scripts/run-tests.js
- src/common.js
- test/common.js
- test/grep.js
- test/pwd.js
- test/rm.js
- test/sed.js
- test/set.js
- test/to.js
- test/toEnd.js
- test/touch.js
I think this is worth it because:
1. `jshint` is udpated, so we'll get whatever bug fixes there may have been as well as performance improvements
2. This is now an npm package script instead of part of `run-tests.js`. Although cutting down on code is nice, this really shines in that it exposes linting to the commandline (so you can lint without re-running tests if you choose), and it lets jshint figure out which files to lint, instead of using `common.expand()` to expand the `*` character for Windows
3. I removed most re-declarations of variables just because I know that's an issue for eslint, and I know we may migrate to use that in the future. This wasn't required by jshint, however
4. I made linting a bit stricter, and actually caught some confusing parts of the code
5. Linting now …
> chore: update jshint and move it to an npm script

- .travis.yml
- package.json
I noticed an issue we had was that if someone fails to generate docs, it isn't always clear to them that travis is failing for that reason. I wrote out my [own module](https://github.com/nfischer/travis-check-changes) to handle this sort of situation, but with hopefully nicer error reporting.
This PR updates ShellJS to use the module as a dev dependency, with an error message that is hopefully a bit more explanatory than what we had before.
> chore: clarify message for when docs are not generated

- make.js
This reverts commit 5a31c7c4369b5e6dbf71b005d040c525ec07b68e from #431.
This reverts the deprecation of the make command as noted in #340.
> chore: revert depreciate shelljs/make (#431)

- shell.js
- src/common.js
I think this is one of the first steps we'll need to take in order to create a better setup for creating new commands/plugins. Now, contributors need only specify that their command can receive input from a pipe with the `receivesPipe` option set to `true`, instead of modifying the array that used to explicitly contain each command that could receive input from a pipe.
This cuts out one more spot where contributors need to make a modification.
> refactor: expose pipe-ability to command configuration

- src/mv.js
Fixes #1 
Error reporting seems to work correctly: if an error is encountered at any point, the reported message still indicates it's the `mv` command that had the error.
I couldn't think of a way to mock tests for this, but let me know if you can think of something.
> fix(mv): works across partitions

- RELEASE.md
- package.json
Similar to shelljs/shx#63, this switches to the new release script. I also updated the release steps accordingly. Feel free to double check the release steps I wrote out, since we want to be sure these are in the right order.
> chore: update release process

- shell.js
- src/cat.js
- src/cd.js
- src/chmod.js
- src/common.js
- src/cp.js
- src/dirs.js
- src/echo.js
- src/exec.js
- src/find.js
- src/grep.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/pwd.js
- src/rm.js
- src/sed.js
- src/set.js
- src/sort.js
- src/tail.js
- src/tempdir.js
- src/test.js
- src/touch.js
- src/which.js
This is based off the plugin API spec. All ShellJS commands now register themselves from within their source file. The only modification that is required to `shell.js` is to put:
```javascript
//@include ./src/foo
require('./src/foo');
```
for a hypothetical new command named `foo()` implemented inside of `src/foo.js`.
In a possible future plugin, the `//@include` would be unnecessary (that's for our internal docs) and the `require()` statement would be all that is needed by the plugin's end-user. The plugin hypothetically doesn't even need to export anything, because the plugin author can require ShellJS as a peer dependency and modify the existing ShellJS instance using a call to `common.register()`.
Let's wait to merge this until after #452 is merged, since I can quickly resolve the …
> refactor: commands now register themselves

- shell.js
- src/uniq.js
- test/uniq.js
Fixes the new uniq() command to use the new format. This also adds a test to make sure it permits globbing (this was broken after merging #452 because of a recent refactor).
> refactor: hook new uniq() command using new format

- shell.js
If a plugin was imported before the ShellJS instance was created, the user's script would crash (`common.register` wouldn't be instantiated yet). Now plugins can be imported either before or after the ShellJS instance is created.
One really cool consequence of this fix is that now plugins are compatible with the `shelljs/global` script:
```js
require('shelljs-plugin-open');
require('shelljs/global');
open('file.txt'); // it works!
```
Another cool consequence is that this would allow me to rewrite [shelljs-exec-proxy](https://github.com/nfischer/shelljs-exec-proxy) as a ShellJS plugin, which would let it play nicely with other plugins (such as shelljs-plugin-open).
> fix: resolve a cylcic-dependency problem

- README.md
- src/common.js
- src/cp.js
- src/find.js
- src/grep.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/rm.js
- src/sed.js
- src/sort.js
- src/tail.js
- src/test.js
- src/touch.js
- src/uniq.js
This is roughly in-line with what was proposed for the plugin API. This moves option parsing as part of `common.wrap()`, so contributors don't need to worry about making the call themselves. By default, `common.wrap()` acts as it did before, and will only parse options if options are specified when the plugin is registered.
For trickier commands, like `chmod()` and `set()`, which sometimes need special parsing, the contributor can choose to parse these commands with an explicit call to `common.parseOptions()`.
This deviates from the plugin API draft in that command options are passed in via the `cmdOptions` attribute, which I believe is more descriptive than an anonymous parameter to `common.register()`. This also makes it easier to leave option parsing optional.
> refactor: move option parsing into common.wrap()

- src/cat.js
- src/cd.js
- src/chmod.js
- src/common.js
- src/echo.js
- src/find.js
- src/grep.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/pwd.js
- src/rm.js
- src/sed.js
- src/sort.js
- src/tail.js
- src/touch.js
- src/uniq.js
- src/which.js
This lets you return a plain JS string (like before), but pass the `wrapOutput` option to `common.register()` in order to wrap this string in a ShellString. This wraps it with the following default parameters (which I think will work properly most of the time):
```js
return myReturnValue;
// This gets wrapped to imitate the statement:
return new common.ShellString(myReturnValue, common.state.error, common.state.errorCode);
// If any errors have occurred, put these in the .stderr attribute
// Whatever the resulting exit code is (0 unless there's an error), set that for the .code attribute
```
By default, `common.register()` works as before (so collaborators must opt-in for this feature). This lets functions return non-string output, or return a custom-built ShellString (if these default …
> refactor: add wrapOutput option to auto-ShellString-ify command output

- plugin.js
- shell.js
- test/plugin.js
After more experimentation, I realized that #482 wasn't a perfect approach, but that this would be a better one. Even after #482, `shell.error()` was actually broken. This fixes that issue.
This also starts differentiating internal implementations (`src/common.js`) from exposed parts of the plugin API (`plugin.js`). This is of course still far from a complete plugin API, but this should be enough to make simple plugins (and still get benefits like globbing, shelljs-style error signaling, etc.).
All implementations are still within `src/common.js`, and internal commands still rely on that directly, but external plugins are intended to use `var plugin = require('shelljs/plugin')` to get functions like `plugin.register()`. This also makes it easy to modify the plugin API without breaking …
> refactor: expose plugin utils & add initial tests

- shell.js
- src/common.js
- src/to.js
- src/toEnd.js
- test/to.js
- test/toEnd.js
Fixes #487 
This implements the `pipeOnly` option to `wrapOptions`. This is false by default.
This checks for conflicts between `pipeOnly` and `canReceivePipe` and throws an exception.
This also refactors some code to take advantage of these new changes. Two test cases were modified in order to give better error messages (in case globbing ever breaks for `.to()` or `.toEnd()`).
> refactor: allow pipeOnly commands (methods on ShellStrings)

- src/common.js
- src/exec.js
This is another refactor idea I got from one of @ariporad's refactors (I forget where exactly).
Instead of specifying `notUnix: true`, this specifies `unix: false` (probably a bit clearer down the road).
> refactor: switch from notUnix to unix in wrap()

- src/common.js
Not a big deal, but I figure we may as well rely on the native implementation when it's available.
We could consider using [this package](https://www.npmjs.com/package/object-assign) instead, but it's probably not a big concern either way.
> refactor: switch common.extend() to Object.assign ponyfill

- src/common.js
- test/common.js
Found this bug by looking at @ariporad's branch [here](https://github.com/shelljs/shelljs/commit/50e741e2e08e5e521e012d53d1fb3b19bfc0191e#diff-2c36c683dff5798fefed561dbec17803R158). Credit for finding this goes to him.
I added a unit test for it, and sure enough, the unit test won't pass unless this patch is applied.
> fix: conflicting options now properly override each other

- src/cat.js
- src/cd.js
- src/chmod.js
- src/common.js
- src/cp.js
- src/dirs.js
- src/echo.js
- src/exec.js
- src/find.js
- src/grep.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/pwd.js
- src/rm.js
- src/sed.js
- src/set.js
- src/sort.js
- src/tail.js
- src/tempdir.js
- src/test.js
- src/to.js
- src/toEnd.js
- src/touch.js
- src/uniq.js
- src/which.js
- test/plugin.js
This PR accomplishes:
- `globStart` defaults to 1
- commands have argument globbing by default
- to opt out of globbing, use `allowGlobbing: false`
Commands have been refactored to take advantage of this new default value.
Also, this PR begins to store default values in a JS object for each `wrapOption`, which will probably make it easier to keep track of the defaults in the long run. Because this uses `common.expand()`, this will have a slight conflict with #490 (this is just because I renamed `expand` to `objectAssign` in that PR). I'll resolve the conflict after either PR is merged and update accordingly.
This might be a good time to discuss if we want `wrapOutput` to be true by default, since it seems like it'll be the norm for a command to use that option.
> refactor: glob by default for commands

- src/common.js
- test/plugin.js
Commands are no longer overwritten by default (probably safer and smarter), but there is an option to allow that behavior if necessary (like if someone hypothetically writes a better `find()` command to replace the builtin one).
> feat: add overWrite option for commands

- src/cat.js
- src/common.js
- src/exec.js
- src/grep.js
- src/head.js
- src/sed.js
- src/sort.js
- src/tail.js
- src/uniq.js
- test/plugin.js
`readFromPipe()` no longer requires `this` to be passed in as the first parameter.
Fixes #485
> refactor: readFromPipe() requires no arguments

- README.md
- src/echo.js
- test/echo.js
Fixes #510 
The only real difference in behavior is that `echo('-e', message)` won't print the literal `-e` (since Bash's `echo -e` wouldn't).
> fix: echo supports -e option properly

- README.md
- src/cp.js
- test/cp.js
Only update when the source file is older than the destination, or the
destination file is missing.
Fixes #526
> feat: cp -u option

- src/test.js
- test/test.js
> Fix: Remove default glob from shell.test (fixes #529)

- .travis.yml
This version of Node was already unsupported as of ShellJS v0.7
> chore: remove v0.10 from Travis CI

- package.json
- test/pipe.js
I used the FIND command which ships with Windows as something to
pass data through.
The test checks that a POSIX-like find(1) exists and skips the tests
if this condition is true because Windows-provided FIND is incompatible
with find(1).
> Get pipe tests running on Windows.

- src/cp.js
- test/cp.js
Prevent maxdepth from limiting the total number of copies, only allow it to
limit the maximum depth
Fixes #547
> fix: maxdepth doesn't limit total number of copies

- src/common.js
Fixes #483.
Instead of exiting the process with `process.exit(1)`, simply throw an error. This way, the error can be caught by Node itself. If the error is not caught, the error is still printed, and the process exits with a `1`.
> Safely exit by throwing an error

- src/exec.js
If an error exists, but has no error code, it defaults to 1 (a common code for
most Unix commands). Tests have been omitted since this is an edge case that is
difficult to reproduce.
Fixes #536
> fix: handle code-less errors more carefully in exec

- .eslintignore
- .gitignore
- package.json
Use `nyc` for test coverage and ignore all nyc-related files in git & eslint.
This increases testing time (~35sec -> ~60sec on my 4-core machine).
Fixes #347
> chore: set up test coverage

- src/mkdir.js
- test/cp.js
- test/ls.js
- test/mkdir.js
- test/rm.js
Adds tests to make sure that non-normalized paths (i.e. path/to/./dir) are
valid for a few commands, including mkdir() which previously failed when given
the -p flag.
Fixes #634
> fix: allow non-normalized paths as input to mkdir

- README.md
- package.json
- shell.js
- src/common.js
- test/cd.js
- test/cp.js
- test/dirs.js
- test/find.js
- test/global.js
- test/grep.js
- test/ln.js
- test/ls.js
- test/mkdir.js
- test/mv.js
- test/plugin.js
- test/popd.js
- test/pushd.js
- test/pwd.js
- test/rm.js
- test/sed.js
- test/set.js
- test/to.js
- test/toEnd.js
- test/touch.js
This adds `.reset()` and `.resetForTesting()` to `shell.config` and use `.resetForTesting()` as a standard set-up for unit tests.
This also adds `npm run test-no-coverage`, since testing with coverage every time gets pretty slow.
`.reset()` is implicitly tested by checking default values for `shell.config`. `.resetForTesting()` is relied upon by all unit tests.
> refactor: add config.reset() and .resetForTesting()

- src/common.js
- src/exec.js
- test/common.js
- test/exec.js
- test/set.js
- test/shjs.js
- test/utils/utils.js
Switch to using `common.execPath` instead of `process.execPath` directly and warn
electron users if we were unable to find the correct path to NodeJS.
This should be safe to merge into master because exec didn't work before anyway.
Fixes #633
> refactor: create common.execPath

- .eslintrc.json
- src/chmod.js
- src/common.js
- src/dirs.js
- src/exec.js
- src/set.js
Multi-line lists and objects should have a trailing comma. This keeps things stylistically consistent, while still having good compatibility.
> chore(lint): Enforce a trailing comma for multi-line

- src/find.js
- test/find.js
Fixes #653 
Fixes `find` so that it returns a shell error if passed a non-existent path.
> Fix find ENOENT

- src/which.js
- test/which.js
With a `-a` option it will return an array of all matched binaries. Stdout is formatted as needed (joined with `\n` all binaries and `\n` is added to the end).
I've tested it on Mac OSX and Windows.
> feature: add -a option for which command

- RELEASE.md
Miscellaneous changes.
`npm run gendocs` is actually done as part of the CI, so it isn't necessary to run it manually for a release.
> docs: clean up RELEASE.md

- src/ls.js
- test/ls.js
This PR continues #665 and fixes #666.
From `node-glob` repo:
>Note that symlinked directories are not crawled as part of a **, though their contents may match against subsequent portions of the pattern. This prevents infinite loops and duplicates and the like.
Therefore, the current pattern (`/**/*`) takes the first level of files inside symlinked directories. This PR changes it to `/**` which does not follow symlinks.
Now both `ls` and `find` only show the symlink directory as a single entry. `ls -RL` follows it.
> Modified glob pattern. Fixes #666

- src/which.js
Use path.delimiter instead of explicit conditional. Try to reuse
repeated code blocks. Remove logical negation at the end
of the function to improve readability.
Blocked on #655 
Fixes #656
> refactor: reduce repeated code in which()

- README.md
- src/exec.js
- Add @freitagbr to the bottom of the README
- Remove docs about shjs (it's not well supported)
- Remove docs about coffeescript (we don't do anything special for
coffeescript anyway)
- Modify the section about shelljs/global, since we strongly recommend
avoiding this now
- Rewrite the code example to use `require('shelljs')` instead of
shelljs/global
- Mention ESLint next to JSHint
- Reformat sections with long lines to be 80 columns
> docs: miscellaneous README changes

- .travis.yml
- README.md
- package.json
Add codecov to ShellJS
Partial fix for #671
> chore: add codecov

- src/common.js
- src/cp.js
- src/mkdir.js
- src/mv.js
- src/rm.js
- src/tempdir.js
- src/test.js
- src/to.js
- src/toEnd.js
No change in logic.
Add `/* istanbul ignore next */` lines for hard-to-test lines so that
they don't count against us during code coverage.
I've also adjusted comments that I found confusing, and changed some
formatting.
Partial fix for #671
> test: don't count hard-to-test lines for coverage

- test/common.js
- test/cp.js
- test/mv.js
- test/rm.js
- test/toEnd.js
No change in production logic.
This adds missing tests to improve test coverage. This does not change
ShellJS behavior at all--all test cases are testing already-working
functionality.
One test case has been renamed for clarity.
For the "omit directory if missing recursive flag" case, we were
actually already testing that in another case, but we were testing
multiple things in that test case. It's better to test this one error
condition explicitly in its own case.
When adding real tests for `parseOptions()`, we need to explicitly clear
`common.state.error` because we're testing an internal function, not a
wrapped command.
Partial fix for #671
> test: add misc. tests to improve coverage

- test/common.js
- test/ls.js
- test/pipe.js
- test/to.js
- test/toEnd.js
No change in production logic.
> Refactor tests to improve readability

- appveyor.yml
- package.json
Invoke codecov on appveyor builds too, so that we can get coverage for
Windows-specific lines of code.
Partial fix for #671
> chore: add codecov script to appveyor CI

- src/common.js
- test/common.js
- test/mv.js
- test/pushd.js
The error output produced by `shell.error()` or `result.stderr` should
not be inconsistent between platforms. This ensures that path separators
are always printed by ShellJS as `/` instead of as `\` on Windows. This
should allow scripts using ShellJS to be more consistent cross-platform.
We had only one test case which relied on the old behavior, and it's in
`pushd`, which we don't any issues for. Since it's only the error output
that's changed, it's probably a reasonable fix to make.
Fixes #681
> fix: convert error output to be consistent cross-platform

- src/cp.js
- test/cp.js
If `cp` is passed a destination that is location of a source file, in effect, copying a file to itself, the source file will become empty. This prevents this situation form happening by verifying that the destination is a different location than the source.
Fixes #678
> Fix cp overwriting identical files

- src/common.js
- test/common.js
For the case where `parseOptions()` is passed a string that does not
start with a hyphen, we should reject this string instead of returning
the same value. This has no change on any other test cases, and should
not affect any commands since we are careful about what input we pass to
`parseOptions()`
This also adjust how we were handling error cases in the function. We
were previously using two different calls to `common.error()`, one for
if `errorOptions` is passed, and one without. This hurts readability,
because it reads like "if we have errorOptions, then this is an error,
and if we don't then it's also an error," instead of the more
appropriate, "we reached an error case and should use errorOptions if
it's available, otherwise we should signal an error without using it."
We now reject …
> refactor(parseOptions): better handle errors

- src/grep.js
- src/sed.js
- src/sort.js
- src/uniq.js
Splits and joins on newlines only.
Fixes #645 .
> fix(grep, sed, sort, uniq): Split only on newline characters

- src/rm.js
- test/rm.js
Fix the behavior of `rm` such that:
1. `rm('-rf', 'link_to_dir/')` deletes contents of real dir, but keeps dir and symlink
2. `rm('-rf', 'link_to_dir')` deletes the symlink itself
Fixes #587
> Remove contents of symlink to dir with rm -rf

- test/common.js
- test/cp.js
- test/exec.js
- test/set.js
- test/shjs.js
No change in logic.
This removes unnecessary imports of `common.js` in favor of the `shell`
package.
> refactor: remove unnecessary common.js imports

- src/common.js
- src/cp.js
- test/common.js
- test/cp.js
> Fix common.expand error

- src/echo.js
- test/echo.js
- test/utils/mocks.js
Fixes #622 
Adds mocks for `process.stdout.write` and `process.stderr.write` that allows the written values to be extracted. This way, we can inspect the output of `echo` without actually outputting to stdout.
> Echo test mocks

- src/cat.js
- src/head.js
- src/sort.js
- src/tail.js
- src/uniq.js
- test/cat.js
- test/head.js
- test/sort.js
- test/tail.js
- test/uniq.js
We previously did not handle directories very well for many of our commands (would immediately error out). This fixes that.
* `cat()`: did not handle directories as inputs, now it gracefully errors
* `head()`: same thing. It also had a typo in a test.
* `sort()`: same thing. It had the same typo.
* `tail()`: same bug, and same typo.
* `uniq()`: did not handle directories as inputs. Did not handle directories as outputs. Did not handle non-existent inputs (this slipped through because of a test typo). All are treated as errors.
Fixes #707
> Properly handle directories as arguments

- src/mkdir.js
- test/mkdir.js
In particular, this fixes:
- if we try to overwrite a file with a mkdir
- if we try to create a subdirectory of a file
- adds `continue: true` in spots where we missed it
Fixes #720
> fix(mkdir): improve error handling around files

- src/cd.js
- src/common.js
- test/cd.js
Deprecates `common.getUserHome` and provides a warning about the deprecation. Also replaces all of the internal uses of `common.getUserHome` with `os.homedir`.
Fixes #683
> Deprecate common.getUserHome, advise using os.homedir instead

- .travis.yml
- README.md
- package.json
- src/cd.js
- src/common.js
- src/echo.js
- src/exec.js
- src/grep.js
- src/sed.js
- src/sort.js
- src/tempdir.js
- src/uniq.js
- test/cd.js
- test/common.js
- test/echo.js
- test/exec.js
- test/utils/mocks.js
Like #650 but with the merge conflicts resolved.
> Merge dev into master

- src/head.js
- test/head.js
This adds a test for `head()` on the right-hand side of a pipe. This also
removes the try-catch surrounding `fs.openSync()`, because it was unreachable
code. `fs.existsSync()` guarantees that the file exists, and `fs.openSync()`
only throws if the file does not exist, according to official documentation.
I see 100% line coverage for `src/head.js` when running:
```sh
$ nyc --reporter=text --reporter=lcov ava --serial test/head.js`
```
Fixes #741
> test(head): improve coverage

- src/exec.js
- test/exec.js
No logic change.
This adds one test to cover some missing lines, and adds some `istanbul ignore`
directives.
I see 100% line coverage for `src/exec.js` when running:
```sh
$ nyc --reporter=text --reporter=lcov ava --serial test/exec.js`
```
Fixes #742
> test(exec): add tests for coverage

- package.json
- test/chmod.js
- test/cp.js
- test/exec.js
- test/ls.js
- test/mkdir.js
- test/rm.js
- test/test.js
- test/touch.js
- test/utils/utils.js
- test/which.js
This adds `skipOnWin` and `skipOnUnix` to help us manage our platform-dependent
tests. These methods give a nice warning message when we skip tests. We may also
consider adding warnings when running platform-dependent tests.
Part of the motivation for this is if we ever update to AVA v0.19. This version
requires at least one assertion per test case. While this could be disabled with
an AVA setting, we instead benefit from warnings for any case when we
unintentionally skip assertions.
This adds chalk as a dev dependency to enable colored messages.
> chore: add skipOnWin and skipOnUnix test helpers

- package.json
- test/cat.js
- test/cd.js
- test/chmod.js
- test/common.js
- test/config.js
- test/cp.js
- test/dirs.js
- test/exec.js
- test/find.js
- test/global.js
- test/grep.js
- test/head.js
- test/ln.js
- test/ls.js
- test/mkdir.js
- test/mv.js
- test/pipe.js
- test/plugin.js
- test/popd.js
- test/pushd.js
- test/rm.js
- test/sed.js
- test/set.js
- test/sort.js
- test/tail.js
- test/test.js
- test/touch.js
- test/uniq.js
This updates tests for `AVA` 19.0.0+.
`AVA` 0.18.0 has a breaking change which changes the current working directory
for tests. As a result, we need to change 'resources' -> 'test/resources' (and
similar path changes).
`AVA` 0.19.0 has a breaking change that all tests must run at least one assert.
This breaking change was already resolved by #746, so no change was necessary in
this PR.
This updates to `AVA` 0.21.0, since there are no other breaking changes.
> refactor(test): update AVA and refactor tests

- src/ls.js
- test/ls.js
Fixes #733 by specifically checking if the stat'ed file is a symlink and that the linked file is a directory.
> Fix ls not following links to directories by default

- README.md
- src/exec.js
- test/exec.js
Fixes #675 by adding support for the `'encoding'` option to `exec`. It technically supported the `'encoding'` option before, but the return values of `stdout` and `stderr` did not honor the encoding. Now, they will.
> Add "encoding" option to exec

- package.json
This sets 2 AVA options:
* `serial`: same behavior as the CLI flag, which this replaces
* `powerAssert`: if an assert fails, it will inspect all objects involved in
the failed assert. This causes readability issues if `t.falsy(shell.error())`
breaks, since it inspects all of `shell` (which is way too large).
AVA options are a little easier to manage than CLI options (we only update one
place instead of 2 in `package.json`).
> chore: set AVA options

- src/tempdir.js
- test/exec.js
Also removes unnecessary guard code leftover from old versions.
> chore: clean up refs to unsupported node versions

- test/common.js
Fixes #714 
Removes the `t.falsy(shell.error())` checks from methods that can't set the error state.
> Remove unnecessary shell.error checks from common tests

- test/ls.js
Fixes #732 
Adds a single test to `test/ls.js` that runs `ls` on a single file, which is not covered by the existing tests.
> Add a test for ls for a single file

- src/cat.js
- src/cd.js
- src/chmod.js
- src/common.js
- src/cp.js
- src/find.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/rm.js
- src/sort.js
- src/tail.js
- src/tempdir.js
- src/test.js
- src/touch.js
- src/uniq.js
- src/which.js
- test/chmod.js
- test/cp.js
- test/head.js
- test/ls.js
- test/mkdir.js
- test/sort.js
- test/tail.js
- test/touch.js
- test/uniq.js
Fixes #745 
Adds two new methods to `src/common.js`, `common.statFollowLinks` and `common.statNoFollowLinks`, which wrap `fs.statSync` and `fs.lstatSync`, respectively. This change is meant to improve readability and clarify intent.
> Wrap fs.statSync and fs.lstatSync

- src/exec-child.js
- src/exec.js
- test/exec.js
This PR refactors `shell.exec()` by putting its child process in a separate code
file. This also slightly cleans up dead code.
There's more potential to clean this up (e.g. exit status), but this is a good
enough start.
Issue #782
> refactor(exec): move child process to source file

- src/exec-child.js
- src/exec.js
This uses `child_process.execFileSync` instead of `execSync` to launch the child
process. This further reduces the attack surface, removing a possible point for
command injection in the ShellJS implementation.
This does not affect backwards compatibility for the `shell.exec` API (the
behavior is determined by the call to `child_process.exec` within
`src/exec-child.js`).
Issue #782
> Use execFileSync to launch child process

- src/exec-child.js
- src/exec.js
This parameter isn't needed, we can easily rely on exit code status for this.
Eliminating the parameter reduces file IO, code complexity, and removes a busy
loop.
Issue #782
> Remove codeFile parameter

- package.json
This is to fix an issue related to the most recent node 8.x.y versions.
Fixes #803
> chore: update nyc dependency

- src/exec-child.js
- src/exec.js
The `paramsFile` is obsolete now that we use `execFileSync()` for our
internal implementation. Instead, we pass parameters to the child
process directly as a single commandline parameter to reduce file I/O.
Issue #782
> refactor(exec): remove paramsFile

- src/common.js
- test/plugin.js
This reworks the plugin API such that:
- Unable to register a command with unknown wrap-options
- `TypeError` raised for wrap-option type mistakes
- Remove the `overWrite` option (it's unused, probably safest to not
expose for now)
- `cmdOptions` defaults to `null` instead of `false` for type
consistency (no change to default behavior)
- Move `pipeMethods` logic into `_register`, since it makes more sense
there
This is not expected to have any effect on existing plugins.
> refactor: harden plugins against unknown options

- src/exec-child.js
- src/exec.js
This reverts commit 64d5899abc86dd7b7fa84455c0ce3551786c4b5b.
Reason for revert: If stdin is large, then the param object can become
an extremely long string, exceeding the maximum OS size limit on
commandline parameters.
Original change's description:
> refactor(exec): remove paramsFile (#807)
>
> The `paramsFile` is obsolete now that we use `execFileSync()` for our
> internal implementation. Instead, we pass parameters to the child
> process directly as a single commandline parameter to reduce file I/O.
>
> Issue #782
Fixes #818
> Revert "refactor(exec): remove paramsFile (#807)"

- .eslintrc.json
This enforces that files should not end with blank lines (i.e. more than
one trailing newline). The `eol-last` rule (inherited from airbnb's
config) already enforces that files end in at least one trailing
newline, so adding this rule enforces that it ends in exactly 1.
See https://eslint.org/docs/rules/no-multiple-empty-lines and
https://eslint.org/docs/rules/eol-last for more information.
Inspired by #809.
> chore(lint): don't allow excess trailing newlines

- src/exec.js
- test/exec.js
Fixes #734 
Removes `common.error('internal error')` from `exec`, allowing any internal errors in `exec` to be wrapped by `ShellJSInternalError` instead.
> Remove separate "internal error" from exec

- package.json
This bumps the version of our dependency, shelljs-release. I just cut
the 3.0 release for shelljs-release, which contains support for the
`--otp` flag, as well as the significant refactoring work we put in.
> chore: update shelljs-release version

- appveyor.yml
This changes appveyor from using the latest npm version to only using
the preinstalled npm version. This is safer, because it's guaranteed to
be a compatible version.
Fixes #844
> chore(appveyor): do not use latest npm

- .travis.yml
Knowing the `npm` version was a huge help to debugging issue #844. For
some reason, we output this on appveyor but not on Travis. This PR fixes
that.
> chore: output npm version in travis

- bin/shjs
- test/shjs.js
Fixes #789 
This makes it so that `bin/shjs` cannot be `require`d as a module, and adds a test for this.
> Prevent require-ing bin/shjs

- package-lock.json
- package.json
This reduces install spam by bumping codecov to avoid depending on a
deprecated graceful-fs version, as well as adding a package-lock.json.
> chore: bump dev dependencies and add package-lock

- test/utils/utils.js
This fixes a conflict between mocks.init() and
utils.skipOnWin/skipOnUnix. mocks.init() mocks out process.stderr.write,
which utils.js implicitly depends on.
Instead, preserve stderr.write in a local variable to avoid polluting
mocked stdio and to correctly output warning messages.
Fixes #862
Test: locally apply mocks.init() inside test/which.js
> fix(mocks): fix conflict between mocks and skip

- src/cp.js
- test/cp.js
This is a redo of PR #555.
This rebases, cleans up a test, and fixes a bug (the original PR uses `fs.chown()` instead of `fs.chownSync()`).
Fixes #98
> Fix cp from readonly source

- test/cp.js
- test/echo.js
This renames some tests to be a bit more readable.
> chore: rename some tests

- src/which.js
- test/resources/which/node
- test/which.js
> Fix(which): match only executable files (#657)

- README.md
We don't really use the gitter chatroom right now, so we shouldn't
direct users to chat there. It's best to have issues reported directly
on Github.
This PR removes the gitter badge from the README.
> docs: remove gitter badge

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
- scripts/ci-or-install.js
This adds a script which checks the npm version and runs either `npm ci`
or `npm install` based on support. This is primarily to work around an
issue where `npm install` modifies `package-lock.json` for newer npm
versions.
A side benefit is that `npm ci` is slightly faster than `npm install`.
Fixes #893
> chore(npm): add ci-or-install script

- src/exec.js
- test/exec.js
Based on #861 
Fixes #851 
Fixes #891
> Fix silent exec

- .travis.yml
Apparently, travis hasn't been uploading any coverage data this whole
time. This fixes the command (copied from appveyor).
> chore(ci): fix codecov on travis

- src/common.js
- src/exec.js
- src/tempdir.js
- test/tempdir.js
Previously, the cached `tempdir` value was stored in `common.state`.
Unlike the other `common.state` values, this isn't immediately useful to
other commands (they can just call the tempdir API). So, this moves the
cached value into `tempdir.js`.
This also adds a unit test for the caching behavior, and exposes
test-only helpers to verify this behavior.
Finally, this adds a note to `common.state` that values should generally
be considered read-only, since this can be important for customized
behavior. Although, I recognize our code base has one exception to this
rule (`echo()`), we should strive to maintain this.
Fixes #902
Test: Added a unit test.
> refactor: don't expose tempdir in common.state

- test/sed.js
As discussed as an aside in #900, add test case with an empty file.
> Add test case for sed on empty file

- src/grep.js
- test/grep.js
Resolve an issue where grep returned 0 (with a `\n` as the output), even when the regex doesn't match.
Fixes #900
> fix: Exit 1 with empty string if no match

- src/cp.js
- test/cp.js
Fixed `cp -Ru` ignoring `-u`, and added a test.
Fixes #808
> feat(cp): support update flag when recursing

- .travis.yml
We can safely use `node_js` on all three supported platforms on Travis CI and remove the obsolete scripts.
See https://github.com/shelljs/shelljs/pull/908#issuecomment-442732567
> ci: change language to node_js and remove obsolete scripts

- src/exec-child.js
- test/exec.js
This explicitly checks for maxBuffer errors in exec-child.js and
provides a consistent error message. This modifies the test to verify
this.
Although the error message is now explicit, this is not part of our API,
since it's just tacked onto the end of exec's stderr.
Fixes #915
> fix(exec): consistent error message for maxBuffer

- .travis.yml
- appveyor.yml
- package.json
NYC takes forever on my local machine, and I generally prefer to look at
coverage reports on the website anyway.
This changes `npm test` to run without coverage, and changes our CI to
run `npm run test-with-coverage` instead.
> chore(test): no coverage by default

- README.md
- src/touch.js
- test/touch.js
No change to production logic.
We never had coverage for `touch({'-d': ...})`, so this adds test
coverage. This also updates documentation to clarify the parameter
should be an instance of the `Date` type.
Test: `handles date argument` case
> test(touch): add coverage for -d option

- .travis.yml
- README.md
- appveyor.yml
- src/common.js
- src/touch.js
- test/common.js
- test/touch.js
This adds initial support for long options. This integration tests them
with `shell.touch()` and unit tests them in `test/common.js`. This
documents the new syntax.
This also refactors some of the common internals:
* Creates a new CommandError type to replace the `'earlyExit'` hack
* Clearer Error types for `parseOptions()` exceptions
* Removes side effects from a test which modifies `common.config`
* Fixes appveyor and travis config to run lint (regressed in #920)
Issue #924
Test: touch.js, common.js
> feat(options): initial support for long options

- README.md
- src/cat.js
- src/cd.js
- src/chmod.js
- src/common.js
- src/cp.js
- src/echo.js
- src/exec.js
- src/find.js
- src/grep.js
- src/head.js
- src/ln.js
- src/ls.js
- src/mkdir.js
- src/mv.js
- src/pwd.js
- src/rm.js
- src/sed.js
- src/sort.js
- src/tail.js
- src/test.js
- src/to.js
- src/toEnd.js
- src/touch.js
- src/uniq.js
- src/which.js
No change to logic, only docs.
In v0.7.0, we introduced ShellStrings and changed most methods to return
them. Docs weren't appropriately updated, so this PR cross-links these
methods to the ShellString docs.
This also expands on the ShellString docs themselves, since there was
room to make this clearer.
Fixes #933
> docs: clarify which methods return ShellStrings

- README.md
- src/sed.js
Also remove example featuring line deletion as it does not work since the regex with '\n' will never match anything, because the file content is split by '\n' so there are no '\n's to match at all.
> docs(sed): clarify using `sed` with newlines

- README.md
- src/exec.js
This adds documentation about `shell.exec()`'s inherent vulnerability to
command injection and links to a more detailed security notice.
Issue #103, #143, #495, #765, #766, #810, #842, #938, #945
> docs(exec): document security concerns

- README.md
- src/common.js
- src/exec.js
- test/exec.js
This PR introduces a new boolean `fatal` option for the `exec()` function. Like the existing `silent` option, this new option allows you to override the global `fatal` configuration parameter on a per-command basis, like:
```js
exec('example command', {
fatal: true|false,
});
```
This eliminates the need for the following pattern:
```js
const oldFatal = shell.config.fatal;
shell.config.fatal = false;
exec('some command that might fail');
shell.config.fatal = oldFatal;
```
The old pattern can introduce race conditions in `async` functions, an issue that was surfaced in our code with the new ESLint rule, [require-atomic-updates](https://eslint.org/docs/rules/require-atomic-updates).
> Add boolean `fatal` option to `exec()` function

- test/cp.js
- test/mkdir.js
- test/utils/utils.js
No change to production logic.
This renames test cases with duplicate names, deletes a redundant test,
and uses the public `t.title` API in favor of `t._test.title`.
This is a prerequisite for updating ava.
Issue #969
> test: misc test changes

- package.json
This updates ava and nyc, to suppress npm audit error messages.
Fixes #969
> chore: update dev deps

- src/common.js
Node.js is currently considering printing a warning when a non-existent
property of `module.exports` is accessed while in a circular `require()`
dependency, in order to make it easier to catch issues with circular
dependencies.
In order to avoid printing these warnings for shelljs, checking for the
property’s existence rather than its truthiness suffices.
Refs: https://github.com/nodejs/node/pull/29935
> Silence potentially upcoming circular dependency warning

- src/exec.js
Previously, we just concatenated _tempDir() with '/' and a random
filename. Instead, we should join paths with path.join() to use the OS
path separator.
This is a speculative fix for issue #974, although this may not be
enough to actually make Windows happy.
Issue #974
> fix(exec): join paths correctly

- commands.js
- package.json
- src/cmd.js
- test/cmd.js
This adds an initial implementation of shell.cmd(), which is intended as
the eventual replacement for shell.exec(). This PR does not fully
implement the API, but demonstrates a simple and secure alternative, and
will allow further iteration to cover other use cases in follow-up PRs.
Design doc: https://shelljs.page.link/cmd-design
Issue #495
Test: automated test suite
> feat: add shell.cmd to replace exec

- src/mv.js
At some point options parsing happened inside `_mv()` and `_cp()` but that is no longer the case so a parsed options object should be used instead.
> fix(mv): Fix moving files across volumes

- .travis.yml
- README.md
- appveyor.yml
- package.json
- scripts/check-node-support.js
This adds testing for node v14. This removes testing for node v6 and v7
because codecov breaks on these versions. This omits node v15 because
appveyor doesn't seem to support this version. The nodejs org currently
supports [10, 12, 14, 15].
This makes a couple minor edits to the check-node-support script for
consistency with shelljs/shx#186.
Test: npm run check-node-support
> chore: change supported node versions

- test/cmd.js
No change to logic. This adds a test case to make sure the caret
character ('^') is passed through to the command. This is to make sure
the character is not treated specially on Windows, where it's an escape
character in the shell.
Fixes #1015
> test(cmd): add test for caret char

- test/mkdir.js
This PR is for [#1022](https://github.com/shelljs/shelljs/issues/1022), and aims to expand testing for mkdir -p when (1) a sub-directory already exists, and (2) the sub-directory does not exist. Please let me know if you'd like me to change something, and thank you for the opportunity to work on this issue!
> Added mkdir -p tests for subdirectories

- test/exec.js
This PR is for [#1032](https://github.com/shelljs/shelljs/issues/1032), and removes a .js file extension as a quick fix for a linting error that seems to have appeared recently on ```npm run lint```. Please let me know if you'd like me to change something, and thank you for the opportunity to work on another issue!
> remove file extension

- .documentup.json
- README.md
- RELEASE.md
Since documentup website is no longer available, I have removed all mentions of it in README.md and RELEASE.md
Current documentation is generated using `npm run gendocs` to pull annotated comments and append in README.md. 
`npm test` and `npm run lint` passed. 
Let me know if you have any questions.
> Removed mentions of documentup website 

- src/exec.js
This locks down file permissions used by the internal implementation of
`shell.exec()`.
Issue #1058
Tested manually using the documented scenarios
> fix(exec): lockdown file permissions

- README.md
- src/ls.js
No change to logic. This documents `shell.ls('-l')`'s `.toString()`
override. I noticed this feature was not documented. This string format
should not be depended on by programmatic usage, but it's useful to make
things more human readable.
> docs(ls): document the toString() override

- README.md
- src/chmod.js
File permissions on Windows are weird. This adds a brief note into the
README that this is something to watch out for. As far as I'm aware, WSL
completely avoids the weirdness because it's actually Linux (and so it
follows POSIX).
> docs(chmod): briefly mention Windows file perms

- README.md
- src/cp.js
- test/cp.js
This is a redo of #841.
This adds the `-p` flag to `cp()` to preserve certain attributes, such as timestamps.
Fixes #771
> Add preserve option to cp

- README.md
No change to logic. This documents that we support importing via
`import shell from 'shelljs'`.
Related to issue #1071, although some more investigation is required to
understand why the other syntax doesn't work.
> docs(import): document es6 import command

- README.md
- src/touch.js
- test/touch.js
No change to logic. This expands on the `touch()` command documentation
to make it more obvious how to use multiple options, long options, etc.
This also renames a variable in a test case to make the usage more
obvious.
> docs(touch): clarify docs for touch() command

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. This updates GitHub actions to test up through node
v18.
> chore: update CI to include v18

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. This updates GitHub actions CI to test on node v19 and v20.
> chore: update CI to test against node v20

- shell.js
This changes shell.exit() to use a wrapper function. This is so that shell.errorCode() will have the correct error code after invoking shell.exit(code). This isn't normally relevant, however a caller may be listening for the exit status:
```js
process.on('exit', code => {
shell.exit(shell.errorCode());
});
```
Issue #1013
> fix: shell.errorCode() honors shell.exit(code)

- .github/workflows/main.yml
- package.json
No change to logic. This updates nyc (code coverage tool) to version 15. The main goal is to work around a bug on the latest nodejs LTS versions.
This change indicates it only supports nodejs >= 8.9. Hopefully this is good enough for our purposes since ShellJS currently supports nodejs >= 8.
Fixes #1130
> chore: update nyc to v15

- .github/workflows/main.yml
GitHub is removing all versions < v16 from GitHub actions. I'm trying to keep Node coverage for as long as possible.
Issue #1140
> chore: keep node < 16 around longer

- .github/workflows/main.yml
It looks like 1a1a820569f0883a317944973c15cf34431dd6c2 actually broke codecov. Codecov is currently trying to diff all PRs against the commit before that one, which leads to flagging previously-added lines of code as needing coverage in the current PR.
Let's try removing the token and see if codecov is happy again.
Fixes #1124
> chore: remove codecov token

- shell.js
- test/echo.js
- test/exec.js
- test/exit.js
- test/popd.js
- test/pushd.js
- test/utils/mocks.js
This adds test coverage for the shell.exit() function. This also refactors how we mock stdout/stderr and adds support for mocking process.exit() (which was needed for this change).
While I was writing these tests, I realized there was an edge case I missed in PR #1122. This change fixes that edge case.
Issue #1013
> test: add coverage for exit function

- package.json
Exports shell.js and make.js on package.json so make.js can be imported as "shelljs/make" without require file extension when using ESM.
> Exports shell.js and make.js on package.json

- src/exec.js
- test/exec.js
test: make a test more forgiving for systems with non-standard bash and sh paths
*Edit from @nfischer: this was originally to address #1143, however it appears that bug was fixed in Node.js 21.4 instead. Original PR description below:*
---
By adding a [`w` flag to the write call](https://github.com/nodejs/node/issues/50989). Also made a test more forgiving so it passes on systems that have non-standard `bash` and `sh` binary paths.
This fixes #1143 .
> test: make a test more forgiving for systems with non-standard bash and sh paths

- .github/workflows/main.yml
I tried this recently in 1a1a820569f0883a317944973c15cf34431dd6c2 and then reverted in b8b1c4224d0ec7d631d26c78922c018dd5b895f5. Unfortunately I'm still seeing spurious failures from codecov, so let's try the token one more time.
This time I double checked the token is provided by https://app.codecov.io/gh/shelljs/shelljs/settings. I regenerated the token for good measure.
> chore: try codecov token again

- test/mkdir.js
- test/touch.js
No change to logic. This updates some test cases to create the files
they need inside the temp directory instead of in the repo itself. This
is helpful in case the test case fails early, that way we don't leave
this file behind.
This contributes toward #828, since the change to fast-glob made it
clear that this test was mishandling link files and leaving side effects
in the git repo. However this change is desirably independent of
fast-glob.
> test: create test files inside temp directory

- .github/workflows/main.yml
- scripts/check-node-support.js
No change to logic. GitHub Actions recently dropped some NodeJS configurations from their service. This excludes those configs from our CI.
This also adds Node versions up through v22.
Test: npm run check-node-support
> chore: remove unsupported node configs from CI

- test/config.js
No change to logic. This adds test coverage support for all of the globOptions which share the same name between node-glob and fast-glob.
See https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#compatible-with-node-glob
Issue #828
> test: add test coverage for some globOptions

- README.md
- shell.js
- src/common.js
This removes support for configuring `config.globOptions`. Exposing this variable makes it difficult to change (or upgrade) our glob library. It's best to consider our choice of glob library to be an implementation detail.
As far as I know, this is not a commonly used option: https://github.com/shelljs/shelljs/issues?q=globOptions currently shows no GitHub issues of users using this option, and there was never really a motivation for why this needed to be exposed (#400 exposed the option just because we could, not because we should).
This is one step toward supporting Issue #828.
> deprecate config.globOptions

- src/ls.js
- test/cp.js
Fix Windows test errors in src/ls.js and test/cp.js.  Full `npm run test` now runs clean on Windows 10.
Relates to preparing for fast-glob, https://github.com/shelljs/shelljs/pull/1153 .
> Fix Windows test errors in src/ls.js and test/cp.js.

- package.json
- scripts/check-node-support.js
This updates js-yaml to 4.1.0 and swaps out `yaml.safeLoad()` for `yaml.load()` because the `safe*` functions are deprecated starting in 4.0.0 (the "regular" functions are considered safe).
> chore(dependencies): update js-yaml

- .github/workflows/main.yml
- README.md
- scripts/check-node-support.js
No change to official support. We will still accept patches for non-LTS versions when it's reasonable to support them, especially for the most recent Node release (whether that is odd-numbered or even-numbered). This just lightens up the workload on CI because most of our users are probably running node LTS.
> chore: switch to testing LTS releases only

- README.md
- shell.js
- test/.eslintrc.json
- test/common.js
- test/config.js
- test/cp.js
- test/head.js
- test/ls.js
- test/mkdir.js
- test/mv.js
- test/plugin.js
- test/set.js
- test/sort.js
- test/tail.js
- test/to.js
- test/toEnd.js
This swaps out quote characters to limit how often we need to escape strings. This is just to improve code readability.
Almost all of the changes could be done without changes to .eslintrc, however this amends the lint rule to also permit backtick strings which can be useful to eliminate a few extra instances of quote escaping.
Fixes issue #788
Test: npm run lint
> refactor: unescape quotes

- README.md
- package.json
- shell.js
- src/common.js
- src/ls.js
This removes `node-glob` in favor of `fast-glob`. The main motivation
for this is because `node-glob` has a security warning and I can't
update to `node-glob@9` unless we drop compatibility for node v8.
Switching to `fast-glob` seems to be fairly straightforward, although
some options need to be changed by default for bash compatibility.
Fixes #828
Fixes #1149
Fixes #1148
> refactor: switch to fast-glob

- README.md
- commands.js
- src/cmd.js
- test/cmd.js
shell.cmd() was originally implemented in #866, however was not yet exposed. This command should be ready for people to try out, so this exposes the command by default.
This is still not a full implementation of everything in the https://shelljs.page.link/cmd-design design doc, however this completes the initial phase and is likely good enough to replace most use cases of synchronous shell.exec().
Fixes #495
> feat: expose new shell.cmd()

- commands.js
- scripts/generate-docs.js
- src/exec-child.js
- test/exec.js
No change to logic. This refactors the exec-child.js script to move all of its main logic into a main() function. This function is only invoked if the script is executed, not when it is imported.
Importing the script is now a NOOP instead of throwing an exception. It's still not advisable to import the script, however this can be done if absolutely necessary to trick JavaScript bundlers which try to prune non-imported code files.
Partially related to issue #1160 and #1172.
> refactor: move exec-child logic into main function

- scripts/generate-docs.js
The gendocs script no longer depends on commands.js. This now works by iterating over source files and parsing them directly.
Partially related to issue #1160 and #1172.
Test: npm run gendocs
> refactor: rewrite gendocs script without commands.js

- test/cmd.js
No change to logic. This adds documentation for the test case for
handling newlines.
This also removes a nearby eslint suppression which is no longer
necessary after PR #1184.
Fixes #175
> test: document test for newline in cmd() function

- src/chmod.js
- src/which.js
- test/config.js
- test/find.js
- test/ls.js
- test/set.js
- test/touch.js
- test/which.js
No change to logic. This swaps out Array.prototype.indexOf in favor for Array.prototype.includes() to simplify logic. This does the same for the equivalent String.prototype functions.
Test: npm test
> refactor: prefer includes() over indexOf()

- package-lock.json
- package.json
No change to logic. This updates ava to major version 2. This is not the
latest version, however updating to version 3 is not trivial because of
some breaking changes.
This removes the commandline options from the ava invocation in favor of
moving this into the well-supported ava JSON configuration. This is
required for Windows compatibility, because otherwise Windows won't
properly expand "test/*.js" on the commandline and ava v2 won't expand
this unless it's specified in the JSON config.
Test: npm test
Test: npm run test-with-coverage
> chore: update ava dep

- shell.js
Currently anything that includes shelljs in it's chain cannot be bundled into a singular file due to the dynamic require. By explicitly requiring everything in src, this allows singular bundles through things like esbuild.
> Explicitly require commands

- package.json
We intend for dependent projects to be able to import these files, so this adds them to the explicit list of supported exports.
Fixes #1195
Test: tested this by running shelljs-plugin-open's test suite.
> fix: add global.js and plugin.js to exports list

- test/config.js
No change to logic. This adds unit tests for glob expansion.
This includes one test case for behavior which was broken by v0.9.0 (probably due to the switch to fastglob). This behavior hasn't been fixed yet, so the test is marked as skipped.
Issue #1197
> test: add tests for shelljs glob expansion

- .github/workflows/main.yml
No change to logic. This env variable isn't relevant since we dropped support for older node versions.
> chore: remove unused env var

- package.json
No change to logic. shx has a dependency on shelljs/package.json so that it can read the ShellJS version number. This is useful for shx and probably harmless for other packages (we need to ship the package.json file anyway), so this adds it to the exports list as an optional export.
Fixes #1195
Test: I ran `shx --version` with this copy of shelljs as the dependency
> fix: add package.json to exports list

- shell.js
- src/common.js
Prior to this change, there was a dependency cycle between shell.js and common.js. This refactors code to avoid the cycle.
This was previously reported in #1133. Node.js already worked around the issue in v20.6.1, but it's simpler if we can avoid the dependency cycle on our end anyway.
I tested this with `npm test` and also by running my own script which uses a shelljs plugin. This seems to work correctly in both cases.
> refactor: avoid dependency cycle

- .editorconfig
Adds an editorconfig setting to enforce single quotes in JavaScript files.
> Enforce single quotes

- test/cmd.js
- test/common.js
- test/exec.js
- test/plugin.js
- test/shjs.js
No change to logic. This is a small refactor to use stricter "expectation" arguments for calls to t.throws().
> refactor: use expectations for t.throws

- test/cmd.js
- test/exec.js
- test/pipe.js
This is a followup to PR #1211 to use promises everywhere and migrate away from `test.cb()`. The `test.cb()` function is removed in a future version of ava.
I made an attempt to convert the skipped shell.cmd() async test cases, but async functionality isn't implemented so it's possible the test conversion is not totally correct.
> refactor: prefer promises over test.cb

- .eslintrc.json
- global.js
- scripts/check-node-support.js
- shell.js
- src/cat.js
- src/chmod.js
- src/cmd.js
- src/common.js
- src/dirs.js
- src/exec.js
- src/grep.js
- src/head.js
- src/ls.js
- src/mkdir.js
- src/rm.js
- src/sed.js
- src/sort.js
- src/tail.js
- src/tempdir.js
- src/test.js
- src/to.js
- src/toEnd.js
- src/touch.js
- src/uniq.js
- src/which.js
This configures the eslint config to allow ES6 features. This fixes some lint errors caught in the new config, but this mostly suppresses new warnings.
> refactor: allow es6 language features

- src/common.js
This is supposed to be a NOOP, although for some reason this makes a difference in the ava@6 test framework. This should not have a user-visible effect because CommandError is an implementation detail of this library (it's only thrown if `options.fatal` is off, and it's always caught inside of common.js).
> refactor: use es6 class syntax for CommandError

- package-lock.json
- package.json
- test/.eslintrc.json
This updates ava to v6. This resolves some `npm audit` warnings in our project's devDependencies.
This is a partial fix #1180, although I found more errors when I ran the tests locally on v22.10.0.
Test: npm audit
> chore: update ava

- .github/workflows/main.yml
- scripts/check-node-support.js
- src/cmd.js
Starting in node >= 22.10.0, a commandNotFound error will have `undefined` values for stdout/stderr, whereas in earlier versions these values were `null`.
Fixes #1180
> fix: cmd is compatible with node 22.10

- src/cmd.js
- test/cmd.js
- test/exec.js
- test/resources/exec/slow.js
This adds a dedicated if-condition to handle internal errors from execa (timeout, maxBuffer, etc.) and to distinguish these from "regular" errors (the command executed, but it failed with non-zero status).
> refactor: explicit handling for execa errors

- src/cmd.js
- test/cmd.js
This is an internal refactor to change how we handle execa errors inside of shell.cmd().
This also adds a test case for a command which fails silently to make sure that we handle this case correctly.
> refactor: change how internal errors are handled
